# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fhat <- function(X, N, K, Rsel, stdz) {
    .Call('_EFBA_fhat', PACKAGE = 'EFBA', X, N, K, Rsel, stdz)
}

ghat <- function(fhat) {
    .Call('_EFBA_ghat', PACKAGE = 'EFBA', fhat)
}

Qpval <- function(fhat, K, ndraw, Qts, Qint, blockdiag) {
    .Call('_EFBA_Qpval', PACKAGE = 'EFBA', fhat, K, ndraw, Qts, Qint, blockdiag)
}

fEBA <- function(fhat, ghat, K, ndraw, alpha, blockdiag) {
    .Call('_EFBA_fEBA', PACKAGE = 'EFBA', fhat, ghat, K, ndraw, alpha, blockdiag)
}

rcpp_hello <- function() {
    .Call('_EFBA_rcpp_hello', PACKAGE = 'EFBA')
}

