# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
msboot <- function(nrep, x, Wsel, stdz, ncore) {
    .Call('_EFBA_msboot', PACKAGE = 'EFBA', nrep, x, Wsel, stdz, ncore)
}

tsbootH0 <- function(x, rndraws, ncore) {
    .Call('_EFBA_tsbootH0', PACKAGE = 'EFBA', x, rndraws, ncore)
}

#' @export
fhat_lp <- function(X, N, stdz) {
    .Call('_EFBA_fhat_lp', PACKAGE = 'EFBA', X, N, stdz)
}

#' @export
fhat_pmt <- function(X, N, K, Rsel, stdz) {
    .Call('_EFBA_fhat_pmt', PACKAGE = 'EFBA', X, N, K, Rsel, stdz)
}

#' @export
ghat <- function(fhat_pmt) {
    .Call('_EFBA_ghat', PACKAGE = 'EFBA', fhat_pmt)
}

Qpval <- function(fhat_pmt, K, ndraw, Qts, Qint, blockdiag) {
    .Call('_EFBA_Qpval', PACKAGE = 'EFBA', fhat_pmt, K, ndraw, Qts, Qint, blockdiag)
}

fEBA <- function(fhat_pmt, ghat, K, ndraw, alpha, blockdiag) {
    .Call('_EFBA_fEBA', PACKAGE = 'EFBA', fhat_pmt, ghat, K, ndraw, alpha, blockdiag)
}

rcpp_hello <- function() {
    .Call('_EFBA_rcpp_hello', PACKAGE = 'EFBA')
}

